// Generated by scripts/sync-airbnb-photos.ts — do not edit by hand.
// Re-run `npx tsx scripts/sync-airbnb-photos.ts` to refresh from the live
// Airbnb listing.
//
// Each entry points at files in public/images/listing/ and includes a
// srcSet for responsive loading. Used by property-data.ts IMAGES and the
// Gallery component.

export interface ListingPhoto {
  key: string;
  originalFilename: string;
  room: string | null;
  alt: string;
  src: string;
  srcSet: string;
  width: number;
  height: number;
}

export const LISTING_PHOTOS = [
  {
    "key": "living-room-1-01",
    "originalFilename": "0fb0755d-0c7e-4cb5-a990-779494ef9559.jpeg",
    "room": "Living room 1 image 1",
    "alt": "Living room 1 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/living-room-1-01.jpg",
    "srcSet": "/images/listing/living-room-1-01-400w.webp 400w, /images/listing/living-room-1-01-800w.webp 800w, /images/listing/living-room-1-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "living-room-2-01",
    "originalFilename": "c5e54af7-a0f6-4ee3-87f3-935d8c178d33.jpeg",
    "room": "Living room 2 image 2",
    "alt": "Living room 2 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/living-room-2-01.jpg",
    "srcSet": "/images/listing/living-room-2-01-400w.webp 400w, /images/listing/living-room-2-01-800w.webp 800w, /images/listing/living-room-2-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "dining-area-01",
    "originalFilename": "fb0bad41-d537-4aa6-bc3c-52ec5917bd90.jpeg",
    "room": "Dining area image 2",
    "alt": "Dining area — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/dining-area-01.jpg",
    "srcSet": "/images/listing/dining-area-01-400w.webp 400w, /images/listing/dining-area-01-800w.webp 800w, /images/listing/dining-area-01-1200w.webp 1200w",
    "width": 1200,
    "height": 802
  },
  {
    "key": "bedroom-1-01",
    "originalFilename": "6f2df384-f330-4ffe-a6de-4643f71d0959.jpeg",
    "room": "Bedroom 1 image 2",
    "alt": "Bedroom 1 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-1-01.jpg",
    "srcSet": "/images/listing/bedroom-1-01-400w.webp 400w, /images/listing/bedroom-1-01-800w.webp 800w, /images/listing/bedroom-1-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "game-room-01",
    "originalFilename": "3f21f60d-8c4c-4456-a241-11b26a56dcdf.jpeg",
    "room": "Game room image 3",
    "alt": "Game room — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/game-room-01.jpg",
    "srcSet": "/images/listing/game-room-01-400w.webp 400w, /images/listing/game-room-01-800w.webp 800w, /images/listing/game-room-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "exterior-01",
    "originalFilename": "4f68c757-ca48-4528-88a1-6aaee44811e5.jpeg",
    "room": "Exterior image 2",
    "alt": "Exterior — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/exterior-01.jpg",
    "srcSet": "/images/listing/exterior-01-400w.webp 400w, /images/listing/exterior-01-800w.webp 800w, /images/listing/exterior-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "listing-54ee0570",
    "originalFilename": "54ee0570-3922-4853-8a6c-b2d4088f3e66.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-54ee0570.jpg",
    "srcSet": "/images/listing/listing-54ee0570-400w.webp 400w, /images/listing/listing-54ee0570-800w.webp 800w, /images/listing/listing-54ee0570-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "living-room-1-02",
    "originalFilename": "65cc9bdc-1308-4d01-a0df-1b09ddaab09f.jpeg",
    "room": "Living room 1 image 2",
    "alt": "Living room 1 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/living-room-1-02.jpg",
    "srcSet": "/images/listing/living-room-1-02-400w.webp 400w, /images/listing/living-room-1-02-800w.webp 800w, /images/listing/living-room-1-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "living-room-1-03",
    "originalFilename": "34528ab5-b67e-4ada-a56d-6ebe2591b886.jpeg",
    "room": "Living room 1 image 3",
    "alt": "Living room 1 — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/living-room-1-03.jpg",
    "srcSet": "/images/listing/living-room-1-03-400w.webp 400w, /images/listing/living-room-1-03-800w.webp 800w, /images/listing/living-room-1-03-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "living-room-2-02",
    "originalFilename": "c3c3768f-3ce2-41fa-935b-0386eea9c425.jpeg",
    "room": "Living room 2 image 1",
    "alt": "Living room 2 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/living-room-2-02.jpg",
    "srcSet": "/images/listing/living-room-2-02-400w.webp 400w, /images/listing/living-room-2-02-800w.webp 800w, /images/listing/living-room-2-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "dining-area-02",
    "originalFilename": "ab9428af-b4c7-48e6-b793-2b93ebebb492.jpeg",
    "room": "Dining area image 1",
    "alt": "Dining area — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/dining-area-02.jpg",
    "srcSet": "/images/listing/dining-area-02-400w.webp 400w, /images/listing/dining-area-02-800w.webp 800w, /images/listing/dining-area-02-1200w.webp 1200w",
    "width": 1200,
    "height": 797
  },
  {
    "key": "dining-area-03",
    "originalFilename": "c60f05d4-cce4-40a5-a06f-a098af239499.jpeg",
    "room": "Dining area image 3",
    "alt": "Dining area — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/dining-area-03.jpg",
    "srcSet": "/images/listing/dining-area-03-400w.webp 400w, /images/listing/dining-area-03-800w.webp 800w, /images/listing/dining-area-03-1200w.webp 1200w",
    "width": 1200,
    "height": 800
  },
  {
    "key": "bedroom-1-02",
    "originalFilename": "063c8df6-b539-4a50-ada5-9ad9896c6f54.jpeg",
    "room": "Bedroom 1 image 1",
    "alt": "Bedroom 1 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-1-02.jpg",
    "srcSet": "/images/listing/bedroom-1-02-400w.webp 400w, /images/listing/bedroom-1-02-800w.webp 800w, /images/listing/bedroom-1-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-1-03",
    "originalFilename": "de53f7f4-e676-446a-95a5-dc052c9bf1dd.jpeg",
    "room": "Bedroom 1 image 3",
    "alt": "Bedroom 1 — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-1-03.jpg",
    "srcSet": "/images/listing/bedroom-1-03-400w.webp 400w, /images/listing/bedroom-1-03-800w.webp 800w, /images/listing/bedroom-1-03-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-2-01",
    "originalFilename": "f51ddd26-8b58-405c-9e12-c1422fe7b864.jpeg",
    "room": "Bedroom 2 image 1",
    "alt": "Bedroom 2 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-2-01.jpg",
    "srcSet": "/images/listing/bedroom-2-01-400w.webp 400w, /images/listing/bedroom-2-01-800w.webp 800w, /images/listing/bedroom-2-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-2-02",
    "originalFilename": "8a47fc3e-4416-427a-b477-12eda2798e89.jpeg",
    "room": "Bedroom 2 image 2",
    "alt": "Bedroom 2 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-2-02.jpg",
    "srcSet": "/images/listing/bedroom-2-02-400w.webp 400w, /images/listing/bedroom-2-02-800w.webp 800w, /images/listing/bedroom-2-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-3-01",
    "originalFilename": "4b3c9eb4-2211-42a4-897d-088121b3568c.jpeg",
    "room": "Bedroom 3 image 1",
    "alt": "Bedroom 3 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-3-01.jpg",
    "srcSet": "/images/listing/bedroom-3-01-400w.webp 400w, /images/listing/bedroom-3-01-800w.webp 800w, /images/listing/bedroom-3-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-3-02",
    "originalFilename": "72fc2ea3-2d08-4265-9f88-86b17be237d3.jpeg",
    "room": "Bedroom 3 image 2",
    "alt": "Bedroom 3 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-3-02.jpg",
    "srcSet": "/images/listing/bedroom-3-02-400w.webp 400w, /images/listing/bedroom-3-02-800w.webp 800w, /images/listing/bedroom-3-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-4-01",
    "originalFilename": "1ab5b076-b11d-4f51-98f7-bc68ee7028a0.jpeg",
    "room": "Bedroom 4 image 1",
    "alt": "Bedroom 4 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-4-01.jpg",
    "srcSet": "/images/listing/bedroom-4-01-400w.webp 400w, /images/listing/bedroom-4-01-800w.webp 800w, /images/listing/bedroom-4-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "bedroom-4-02",
    "originalFilename": "290cbe01-65ff-4892-b06c-598058c8b647.jpeg",
    "room": "Bedroom 4 image 2",
    "alt": "Bedroom 4 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-4-02.jpg",
    "srcSet": "/images/listing/bedroom-4-02-400w.webp 400w, /images/listing/bedroom-4-02-800w.webp 800w, /images/listing/bedroom-4-02-1200w.webp 1200w",
    "width": 1200,
    "height": 800
  },
  {
    "key": "bedroom-4-03",
    "originalFilename": "c8f42df2-7565-454e-b00b-cc50d4598725.jpeg",
    "room": "Bedroom 4 image 3",
    "alt": "Bedroom 4 — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/bedroom-4-03.jpg",
    "srcSet": "/images/listing/bedroom-4-03-400w.webp 400w, /images/listing/bedroom-4-03-800w.webp 800w, /images/listing/bedroom-4-03-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "listing-5a438854",
    "originalFilename": "5a438854-66cd-472f-9eb7-ab3798f2ab41.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-5a438854.jpg",
    "srcSet": "/images/listing/listing-5a438854-400w.webp 400w, /images/listing/listing-5a438854-800w.webp 800w, /images/listing/listing-5a438854-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "listing-67d653c0",
    "originalFilename": "67d653c0-ddb0-4f2b-95a5-0b86744b8a91.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-67d653c0.jpg",
    "srcSet": "/images/listing/listing-67d653c0-400w.webp 400w, /images/listing/listing-67d653c0-800w.webp 800w, /images/listing/listing-67d653c0-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "listing-d226d74d",
    "originalFilename": "d226d74d-5ee8-4555-b383-b043c08e99bf.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-d226d74d.jpg",
    "srcSet": "/images/listing/listing-d226d74d-400w.webp 400w, /images/listing/listing-d226d74d-800w.webp 800w, /images/listing/listing-d226d74d-1200w.webp 1200w",
    "width": 1200,
    "height": 1600
  },
  {
    "key": "listing-66883da3",
    "originalFilename": "66883da3-c713-453d-8a8f-25f47c3ee16d.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-66883da3.jpg",
    "srcSet": "/images/listing/listing-66883da3-400w.webp 400w, /images/listing/listing-66883da3-800w.webp 800w, /images/listing/listing-66883da3-1200w.webp 1200w",
    "width": 1200,
    "height": 1600
  },
  {
    "key": "listing-5497032d",
    "originalFilename": "5497032d-b9cf-4a19-9376-a4f372d26642.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-5497032d.jpg",
    "srcSet": "/images/listing/listing-5497032d-400w.webp 400w, /images/listing/listing-5497032d-800w.webp 800w, /images/listing/listing-5497032d-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "listing-fe945c5a",
    "originalFilename": "fe945c5a-edcb-4333-99c4-0aec29b54fc0.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-fe945c5a.jpg",
    "srcSet": "/images/listing/listing-fe945c5a-400w.webp 400w, /images/listing/listing-fe945c5a-800w.webp 800w, /images/listing/listing-fe945c5a-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "backyard-01",
    "originalFilename": "94c81ec9-840b-402a-9256-5967b4331fe5.jpeg",
    "room": "Backyard image 1",
    "alt": "Backyard — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/backyard-01.jpg",
    "srcSet": "/images/listing/backyard-01-400w.webp 400w, /images/listing/backyard-01-800w.webp 800w, /images/listing/backyard-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "patio-1-01",
    "originalFilename": "9ac3ff73-e759-4cd3-b37e-82b62176e326.jpeg",
    "room": "Patio 1 image 1",
    "alt": "Patio 1 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/patio-1-01.jpg",
    "srcSet": "/images/listing/patio-1-01-400w.webp 400w, /images/listing/patio-1-01-800w.webp 800w, /images/listing/patio-1-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "patio-1-02",
    "originalFilename": "4699cdd9-dd98-4d70-a733-db07e9c50884.jpeg",
    "room": "Patio 1 image 2",
    "alt": "Patio 1 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/patio-1-02.jpg",
    "srcSet": "/images/listing/patio-1-02-400w.webp 400w, /images/listing/patio-1-02-800w.webp 800w, /images/listing/patio-1-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "patio-1-03",
    "originalFilename": "90e0b39b-7f43-4550-98b8-1e21e9a0c879.jpeg",
    "room": "Patio 1 image 3",
    "alt": "Patio 1 — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/patio-1-03.jpg",
    "srcSet": "/images/listing/patio-1-03-400w.webp 400w, /images/listing/patio-1-03-800w.webp 800w, /images/listing/patio-1-03-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "patio-2-01",
    "originalFilename": "8a1769a3-ea0a-4a91-b2b3-11fb75b19aaf.jpeg",
    "room": "Patio 2 image 1",
    "alt": "Patio 2 — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/patio-2-01.jpg",
    "srcSet": "/images/listing/patio-2-01-400w.webp 400w, /images/listing/patio-2-01-800w.webp 800w, /images/listing/patio-2-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "patio-2-02",
    "originalFilename": "b777a918-a22e-4ffb-af75-d067bb52307b.jpeg",
    "room": "Patio 2 image 2",
    "alt": "Patio 2 — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/patio-2-02.jpg",
    "srcSet": "/images/listing/patio-2-02-400w.webp 400w, /images/listing/patio-2-02-800w.webp 800w, /images/listing/patio-2-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "balcony-01",
    "originalFilename": "b8aaeac1-fde4-4cac-9c7c-bb7ee775ef9a.jpeg",
    "room": "Balcony image 1",
    "alt": "Balcony — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/balcony-01.jpg",
    "srcSet": "/images/listing/balcony-01-400w.webp 400w, /images/listing/balcony-01-800w.webp 800w, /images/listing/balcony-01-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "balcony-02",
    "originalFilename": "9283282c-08be-4b0d-a6fb-43fc0cf33357.jpeg",
    "room": "Balcony image 2",
    "alt": "Balcony — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/balcony-02.jpg",
    "srcSet": "/images/listing/balcony-02-400w.webp 400w, /images/listing/balcony-02-800w.webp 800w, /images/listing/balcony-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "listing-f647bdd5",
    "originalFilename": "f647bdd5-d4f4-4463-94d8-1cc8047ed49f.jpeg",
    "room": null,
    "alt": "Harbor on 23rd at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/listing-f647bdd5.jpg",
    "srcSet": "/images/listing/listing-f647bdd5-400w.webp 400w, /images/listing/listing-f647bdd5-800w.webp 800w, /images/listing/listing-f647bdd5-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "garage-01",
    "originalFilename": "96dbb870-122b-4165-8d2d-487bd40d84e7.jpeg",
    "room": "Garage image 1",
    "alt": "Garage — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/garage-01.jpg",
    "srcSet": "/images/listing/garage-01-400w.webp 400w, /images/listing/garage-01-800w.webp 800w, /images/listing/garage-01-1200w.webp 1200w",
    "width": 1200,
    "height": 789
  },
  {
    "key": "garage-02",
    "originalFilename": "45f63b49-f51f-4a6c-ac55-1ee128768786.jpeg",
    "room": "Garage image 2",
    "alt": "Garage — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/garage-02.jpg",
    "srcSet": "/images/listing/garage-02-400w.webp 400w, /images/listing/garage-02-800w.webp 800w, /images/listing/garage-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "exterior-02",
    "originalFilename": "654ff099-1a67-4ec1-986d-e20e0e7e4447.jpeg",
    "room": "Exterior image 1",
    "alt": "Exterior — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/exterior-02.jpg",
    "srcSet": "/images/listing/exterior-02-400w.webp 400w, /images/listing/exterior-02-800w.webp 800w, /images/listing/exterior-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "exterior-03",
    "originalFilename": "61675b62-9037-4e19-824e-9fa73aaac4ad.jpeg",
    "room": "Exterior image 3",
    "alt": "Exterior — view 3 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/exterior-03.jpg",
    "srcSet": "/images/listing/exterior-03-400w.webp 400w, /images/listing/exterior-03-800w.webp 800w, /images/listing/exterior-03-1200w.webp 1200w",
    "width": 1200,
    "height": 1715
  },
  {
    "key": "game-room-02",
    "originalFilename": "533bac5d-b460-4acf-9e10-af7cafd8ffc1.jpeg",
    "room": "Game room image 1",
    "alt": "Game room — view 1 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/game-room-02.jpg",
    "srcSet": "/images/listing/game-room-02-400w.webp 400w, /images/listing/game-room-02-800w.webp 800w, /images/listing/game-room-02-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "game-room-03",
    "originalFilename": "555f0872-4aa0-4981-a249-0da84aae8d06.jpeg",
    "room": "Game room image 2",
    "alt": "Game room — view 2 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/game-room-03.jpg",
    "srcSet": "/images/listing/game-room-03-400w.webp 400w, /images/listing/game-room-03-800w.webp 800w, /images/listing/game-room-03-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  },
  {
    "key": "game-room-04",
    "originalFilename": "e5a1e4de-9142-46a2-972f-04b35d855bb3.jpeg",
    "room": "Game room image 4",
    "alt": "Game room — view 4 at Harbor on 23rd — Lake Geneva vacation rental",
    "src": "/images/listing/game-room-04.jpg",
    "srcSet": "/images/listing/game-room-04-400w.webp 400w, /images/listing/game-room-04-800w.webp 800w, /images/listing/game-room-04-1200w.webp 1200w",
    "width": 1200,
    "height": 900
  }
] as const satisfies readonly ListingPhoto[];

export const LISTING_PHOTOS_BY_KEY: Record<string, ListingPhoto> =
  Object.fromEntries(LISTING_PHOTOS.map((p) => [p.key, p]));
